export const IN_PERSON_TEST_PLAYERS = Object.freeze([
  { name_en: "Adrian Hackl", bga_nickname: null, association_id: "AUT" },
  { name_en: "Aleksejs Peguševs", bga_nickname: "Alexey_LV", association_id: "LVA" },
  { name_en: "Árpád Gere", bga_nickname: "g3rappa", association_id: "ROU" },
  { name_en: "Auste Idaite", bga_nickname: "niamniam", association_id: "LTU" },
  { name_en: "Bogdan Curcan", bga_nickname: "game__over", association_id: "ROU" },
  { name_en: "Borislav Aymaliev", bga_nickname: "aymaliev", association_id: "BGR" },
  { name_en: "Carman Tang", bga_nickname: "CTCTCTCTCT", association_id: "HKG" },
  { name_en: "Danial Angelats", bga_nickname: "senglar", association_id: "CAT" },
  { name_en: "Daniel Ayala", bga_nickname: "danielayala94", association_id: "USA" },
  { name_en: "David Faraci", bga_nickname: "Lord Terrycloth", association_id: "GBR" },
  { name_en: "Edzus Kauķis", bga_nickname: "esedzus", association_id: "LVA" },
  { name_en: "Erick Matheus", bga_nickname: "Theus Gladiador", association_id: "BRA" },
  { name_en: "Felipe Tello", bga_nickname: "Telborn", association_id: "CHL" },
  { name_en: "Georgios Kyriazides", bga_nickname: "Asx3t0s", association_id: "GRC" },
  { name_en: "Gert Versteeg", bga_nickname: "Zwollywood", association_id: "NLD" },
  { name_en: "Giulio Tomao", bga_nickname: "GiulioTm", association_id: "ITA" },
  { name_en: "Hogne Jørgensen", bga_nickname: "hognej", association_id: "NOR" },
  { name_en: "Horacio Mastandrea", bga_nickname: "The Alchimist", association_id: "URY" },
  { name_en: "Jani Kutilainen", bga_nickname: "Janikut", association_id: "FIN" },
  { name_en: "Jorim Mella", bga_nickname: "Vainiria", association_id: "CHL" },
  { name_en: "Jozsef Tihon", bga_nickname: "szigfrid", association_id: "HUN" },
  { name_en: "Kestutis Kurienius", bga_nickname: null, association_id: "LTU" },
  { name_en: "Kriss Kaukis", bga_nickname: "krisna", association_id: "LVA" },
  { name_en: "Kyrylo Manakhov", bga_nickname: "adrear", association_id: "UKR" },
  { name_en: "Malin Malmberg", bga_nickname: null, association_id: "SWE" },
  { name_en: "Marlon Marquez", bga_nickname: "Chini_GT", association_id: "GTM" },
  { name_en: "Matt Tucker", bga_nickname: "statmatt", association_id: "GBR" },
  { name_en: "Matthieu Hingant", bga_nickname: "Boulym", association_id: "FRA" },
  { name_en: "Mikhail Lapushynski", bga_nickname: "Gladki_Alex", association_id: "BLR" },
  { name_en: "Nahuel Vignatti", bga_nickname: "Hellkkitte", association_id: "ARG" },
  { name_en: "Naoki Yamaguchi", bga_nickname: "spman2", association_id: "JPN" },
  { name_en: "Nickolas Teo Jia Ming", bga_nickname: "goldie123456", association_id: "SGP" },
  { name_en: "Nico Wellemans", bga_nickname: "N2xU", association_id: "BEL" },
  { name_en: "Nopphon Charoenkham", bga_nickname: "gorufu__", association_id: "THA" },
  { name_en: "Nuria Casanovas", bga_nickname: "Pronom feble", association_id: "CAT" },
  { name_en: "Olexsandr Nosik", bga_nickname: "fanalexn", association_id: "UKR" },
  { name_en: "Oscar Mendez", bga_nickname: "omendiez", association_id: "ESP" },
  { name_en: "Osvaldo del Arco", bga_nickname: "Osvaldo Del Arco", association_id: "MEX" },
  { name_en: "Otto Ikonen", bga_nickname: "Nallerheim", association_id: "FIN" },
  { name_en: "Pavel Raus", bga_nickname: "chonps", association_id: "CZE" },
  { name_en: "Pedro Antunes", bga_nickname: "phoam", association_id: "PRT" },
  { name_en: "Peng Yu-Syuan", bga_nickname: "sakurakim", association_id: "TWN" },
  { name_en: "Raf Mesotten", bga_nickname: "CraftyRaf", association_id: "BEL" },
  { name_en: "Róbert Illés", bga_nickname: "robill", association_id: "HUN" },
  { name_en: "Roey Chalatzy", bga_nickname: "RoeyCh", association_id: "ISR" },
  { name_en: "Salomon Quinones", bga_nickname: "SANAQUI", association_id: "PER" },
  { name_en: "Satoshi Kitamura", bga_nickname: "Kithara", association_id: "JPN" },
  { name_en: "Sergio Antolinez", bga_nickname: "dremkad", association_id: "COL" },
  { name_en: "Sotaro Nagai", bga_nickname: "sou-tata", association_id: "JPN" },
  { name_en: "Stefán Jónsson", bga_nickname: "bobondi", association_id: "ISL" },
  { name_en: "Tatiana Usenko", bga_nickname: "TanyaU", association_id: "UKR" },
  { name_en: "Tim Stratmann", bga_nickname: "HappyTim7", association_id: "DEU" },
  { name_en: "Timofei Gretsenko", bga_nickname: null, association_id: "EST" },
  { name_en: "Tomasz Preuss", bga_nickname: "UY_Scuti", association_id: "POL" },
  { name_en: "Tomislav Buhiniček", bga_nickname: "Tompa99", association_id: "HRV" },
  { name_en: "Vladimir Chendev", bga_nickname: "71st", association_id: "RCP" },
  { name_en: "Vladimir Kovalev", bga_nickname: "Someone_you_know", association_id: "RCP" },
  { name_en: "Xiangyu Qin", bga_nickname: "qazxswedc", association_id: "CHN" },
  { name_en: "Yi Liu", bga_nickname: "King_Deded4d5", association_id: "AUS" },
  { name_en: "Zvonimir Vlaic", bga_nickname: "Bluste", association_id: "HRV" },
]);

